# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-Thumbnail
version:      1.3
version_from: Thumbnail.pm
installdirs:  site
requires:
    Tk:                            8.0.4
    Tk::MultiMediaControls:        1.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
